### ISSUE TITLE
[Correction] 1.18.2 Performance, Incorrect link for DimensionalThreading-Reforged

### ISSUE THREAD

**Issue by Raft08** [TheUsefulLists/UsefulMods#232] opened 2023-06-21 20:03 UTC
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

DimensionalThreading-Reforged

### What section(s) of the list is this correction for?

Performance

### What version(s) does this correction apply to?

1.18.X (Forge)

### What needs correcting?

There is a link that sends to the curseforge page of Dynamic View, It needs to be removed

### Input relevant link(s) which can be used to verify the correction.

https://github.com/CCr4ft3r/DimensionalThreading-Reforged
https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance118.md#forge-118x

![image](https://github.com/TheUsefulLists/UsefulMods/assets/72615320/2e69ad8b-0195-4161-8b07-1146ba96e7a7)
(The mod is only available on GitHub)

**Comment by lrmtheboss** [comment] 2023-10-08 23:21
fixed in 5aa89d3 and duplicate of #249

**Closed by lrmtheboss** 2023-10-08 23:21 UTC
Labels: Correction
